export const cards = [
  {
    id: 1,
    title: "Gold",
    desc: "OTC Vs Exchange",
    img: "https://i.ibb.co/M6NfzTn/gold1.jpg",
  },
  {
    id: 2,
    title: "Equity",
    desc: "Bull Vs Bear",
    img: "https://i.ibb.co/PYX59tD/Sensex-770x433.webp",
  },
  {
    id: 3,
    title: "Options and Futures ",
    desc: "Derivative Market",
    img: "https://i.ibb.co/JQcTsmR/stock-market1.jpg",
  },
  
  
  {
    id: 4,
    title: "Commidity",
    desc: "Primary Products",
    img: "https://i.ibb.co/qgqpVDL/commidity.jpg",
  },
  {
    id: 5,
    title: "Banking",
    desc: "Line Of Credit",
    img: "https://i.ibb.co/6HYrWcF/bank.png",
  },
  {
    id: 6,
    title: "Bonds",
    desc: "Debt Security",
    img: "https://i.ibb.co/H7BgFCs/bonds.jpg",
  },
  {
    id: 7,
    title: "Real Estate ",
    desc: "Land and Property",
    img: "https://i.ibb.co/TWc3PGj/real.jpg",
  },
];
  
  // export const buckets = [
  //   {
  //     id: 1,
  //     img: "https://images.pexels.com/photos/1462935/pexels-photo-1462935.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Web and Mobile Design",
  //     username: "Anna Bell",
  //   },
  //   {
  //     id: 2,
  //     img: "https://images.pexels.com/photos/270408/pexels-photo-270408.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Logo Design",
  //     username: "Morton Green",
  //   },
  //   {
  //     id: 3,
  //     img: "https://images.pexels.com/photos/4144923/pexels-photo-4144923.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Animated GIFs",
  //     username: "Emmett Potter",
  //   },
  //   {
  //     id: 4,
  //     img: "https://images.pexels.com/photos/4348404/pexels-photo-4348404.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Packaging Design",
  //     username: "Freddie Johnston",
  //   },
  //   {
  //     id: 5,
  //     img: "https://images.pexels.com/photos/4458554/pexels-photo-4458554.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Social Media Design",
  //     username: "Audrey Richards",
  //   },
  //   {
  //     id: 6,
  //     img: "https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Illustration",
  //     username: "Dalton Hudson",
  //   },
  //   {
  //     id: 7,
  //     img: "https://images.pexels.com/photos/6077368/pexels-photo-6077368.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Book Design",
  //     username: "Hannah Dougherty",
  //   },
  //   {
  //     id: 8,
  //     img: "https://images.pexels.com/photos/4065876/pexels-photo-4065876.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     pp: "https://images.pexels.com/photos/1680175/pexels-photo-1680175.jpeg?auto=compress&cs=tinysrgb&w=1600",
  //     cat: "Digital Marketing",
  //     username: "Ward Brewer",
  //   },
  // ];
  
  //buvketCardMain
  export const buckets = [
    {
      id: 1,
      img: "https://assets.smallcase.com/images/smallcases/160/SCET_0005.png",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Companies that have been consistently increasing dividends. Extra goodness",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://assets.smallcase.com/images/smallcases/160/SCET_0015.png",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Efficiently managed growing companies experiencing positive momentum",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://assets.smallcase.com/images/smallcases/160/SCTR_0014.png",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "A portfolio of stocks, which will get benefit from the RE sector development.",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Companies focused on the growing middle class. Running India's consumption engine",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Momentum investing: capitalizing on market trends for accelerated returns.",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Efficiently managed growing companies experiencing positive momentum",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "A portfolio of stocks, which will get benefit from the RE sector development.",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Aim to spot High Momentum stocks that are in Action Right Now",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "Generate income from dividends. Basket of individual stocks that pay High dividends.",
      price: 79,
      star: 4,
      username: "Walton Doe",
    },
  ];